const mixkitVideos = require('../scripts/mixkitVideos.js');

module.exports = {
  up: async (queryInterface) => {
    const usersList = [
      {
        username: 'drifterjjlin',
        profile_pic: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80',
        password: 'qwerty',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'jevinkiong3',
        profile_pic: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80',
        password: 'qwerty',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'vtkh2004',
        profile_pic: 'https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=701&q=80',
        password: 'qwerty',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: '7_footskills',
        profile_pic: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1350&q=80',
        password: 'qwerty',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'Sk8er_gurl',
        profile_pic: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80',
        password: 'qwerty',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'hipboi99',
        profile_pic: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80',
        password: 'qwerty',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'curlewreach',
        profile_pic: 'https://images.unsplash.com/photo-1497551060073-4c5ab6435f12?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=667&q=80',
        password: 'qwerty',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'cloudedthrough',
        profile_pic: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=80',
        password: 'qwerty',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'pipershut',
        profile_pic: 'https://images.unsplash.com/photo-1519058082700-08a0b56da9b4?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80',
        password: 'qwerty',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'initiativehand',
        profile_pic: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80',
        password: 'qwerty',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'sowsework',
        profile_pic: 'https://images.unsplash.com/photo-1492446845049-9c50cc313f00?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80',
        password: 'qwerty',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'twinklingaxe',
        profile_pic: 'https://images.unsplash.com/photo-1453396450673-3fe83d2db2c4?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80',
        password: 'qwerty',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'polarbearsweaty',
        profile_pic: 'https://images.unsplash.com/photo-1499996860823-5214fcc65f8f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=702&q=80',
        password: 'qwerty',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'fifteencute',
        profile_pic: 'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80',
        password: 'qwerty',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'deadwoodsell',
        profile_pic: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1350&q=80',
        password: 'qwerty',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'thrifthomerun',
        profile_pic: 'https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80',
        password: 'qwerty',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'ritzyatm',
        profile_pic: 'https://images.unsplash.com/photo-1527203561188-dae1bc1a417f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=658&q=80',
        password: 'qwerty',
        created_at: new Date(),
        updated_at: new Date(),
      },

    ];

    const videosList = [
      {
        user_id: 1,
        description: 'wbu ? #animegir',
        comments: 112,
        music: 'Dance Monkey - Tones andI',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        description: 'Meow-nicure, need to get those stiletto nails 💅🏻 #fyp #catsoftiktok #manicure #meow #munchki',
        comments: 76,
        music: 'original sound - 😈😈😈ရုပ္ဆိုးမေလး😢🥺👿👿👿 - 🌻🌼🌞🌸🌹pi🌼',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        description: 'coba ah ikutan 😁😁 #fyp #fypd #panikgakpaniklahmasakengga',
        comments: 19,
        music: 'Lose You to Love Me - Selena Gomz',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        description: 'Write your names in comment',
        comments: 207,
        music: "Whatta Man (feat. En Vogue) [EP Version] - Salt 'N' Pea",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        description: 'sorry ive only watched one anime my whole life/',
        comments: 39,
        music: 'Shake Dat - by Loui (feat. Lil Ja)',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        description: 'sometimes I confuse myself to',
        comments: 83,
        music: 'Astronaut In The Ocean - Masked Wof',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        description: 'DM me tho 😗 #fyp #tiktoks',
        comments: 200,
        music: 'Unlock it (Lock It) [Jeff Prior Mix] - Charli XX',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        description: 'bagging coffee for takeaway!! more convenient & cheaper than alternative plastic cup',
        comments: 170,
        music: 'HAZ MI BAILE Y ETIQUETAME. - I’M GOL🙌🏾',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        description: 'sorry ive only watched one anime my whole life/',
        comments: 38,
        music: 'Be A Clown - ָ࣪ ۰♥︎ Osuna ࣪꒷',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        description: 'How to Escap',
        comments: 209,
        music: 'Men balls getting smaller - HeartScap2',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        description: '😵😵😵 #foryou #foryoupage #fyp #funn',
        comments: 168,
        music: 'Roxanne - Arizona Zervs',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        description: 'wbu ? #animegir',
        comments: 145,
        music: 'Lose You to Love Me - Selena Gomz',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        description: 'dễ thương quá 🥰🥰🥰 #tiktok #NANNO #thocon #f',
        comments: 15,
        music: 'Bust Your Knee Caps - amana',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        description: 'Ep. 2 Do you tell your siblings everything? #truth #brothe',
        comments: 90,
        music: 'original sound - Laiba👸🏻',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        description: 'interesting cat #cat #pet #cute #catsoftiktok #foryou #fy',
        comments: 173,
        music: 'Lofi Loungemusicc - Cafe lounge resot',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        description: 'Im clearly joking, right? Right. Unless..',
        comments: 234,
        music: 'Obsessed - Mariah Cary',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        description: 'What Chinese will sound like in 50 years! #mryang楊家',
        comments: 230,
        music: "Whatta Man (feat. En Vogue) [EP Version] - Salt 'N' Pea",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        description: 'a ha ha',
        comments: 240,
        music: 'HAZ MI BAILE Y ETIQUETAME. - I’M GOLD🙌🏾',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        description: 'Keep in mind derivatives trading is haram for muslims.',
        comments: 241,
        music: 'Dance Monkey - Tones andI',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        description: 'Reply to @zulhxl I hope this answers your questio',
        comments: 148,
        music: 'Lose You to Love Me - Selena Gomz',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        description: 'a ha h',
        comments: 264,
        music: 'Pull up - Lu Ki',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        description: 'Some not all. #slander #lgbtq #somenotall #Imreadyforthehat',
        comments: 147,
        music: 'original sound - おく',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        description: 'When they say they’re from U.S.A... #fyp #tiktoksingapore #us',
        comments: 251,
        music: 'O Carpinteiro (Conto de Fadas) - nattan & Elias Monkbl',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        description: 'Một chiếc clip dành cho bạn nào muốn chụp ảnh với crush 😂😂😂 #mrvirgo #vzon',
        comments: 60,
        music: 'original sound - user994293815399',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        description: 'The second part of the face off came out today. They will officially be taking each other in a 3 round fight ',
        comments: 119,
        music: 'The Git Up - Benny Blano',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        description: 'I left them alone for 2 mins ',
        comments: 50,
        music: 'original sound - Clarambls',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        description: 'just wondering ;',
        comments: 287,
        music: 'Candy - Doja Ct',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        description: 'Safe to say my head morphed into my neck and I look like a toad 🐸 HAHAH',
        comments: 255,
        music: 'The Git Up - Benny Blano',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        description: 'a ha h',
        comments: 83,
        music: '@dicaoshop 😙😙😙',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        description: 'Very human 😬😬😬 #fyp #foryou #funny #foryoupag',
        comments: 108,
        music: 'The Git Up - Benny Blano',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        description: 'Safe to say my head morphed into my neck and I look like a toad 🐸 HAHAH',
        comments: 82,
        music: 'original sound - Laiba👸🏻',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        description: 'dễ thương quá 🥰🥰🥰 #tiktok #NANNO #thocon #f',
        comments: 40,
        music: 'Bust Your Knee Caps - amana',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        description: 'Chase your Goals 👑 #fyp #sgfy',
        comments: 88,
        music: 'O Carpinteiro (Conto de Fadas) - nattan & Elias Monkbl',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        description: 'no srsly is 3pm why r u runnin',
        comments: 118,
        music: 'original sound - AwesomeMovie3',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        description: 'Some not all. #slander #lgbtq #somenotall #Imreadyforthehat',
        comments: 221,
        music: 'original sound - Laiba👸🏻',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        description: 'sometimes I confuse myself to',
        comments: 39,
        music: 'Copines ac. Isli - Bombxl',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        description: 'Nice guys finish last, that’s why I treat you like trash ❤️(ib: @christian_davis20 ) #fyp #tiktoksg #fuccbo',
        comments: 239,
        music: "Whatta Man (feat. En Vogue) [EP Version] - Salt 'N' Pea",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        description: 'Ep. 2 Do you tell your siblings everything? #truth #brothe',
        comments: 163,
        music: 'Cherrybonbon - Kyary Pamyu Pamu',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        description: 'Been wanting to cover this song for a really long time, hope my pronunciation is ok!😅',
        comments: 265,
        music: 'HAZ MI BAILE Y ETIQUETAME. - I’M GOL🙌🏾',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        description: 'What Chinese will sound like in 50 years! #mryang楊家',
        comments: 283,
        music: 'Men balls getting smaller - HeartScap2',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        description: 'When they say they’re from U.S.A... #fyp #tiktoksingapore #us',
        comments: 149,
        music: 'baby I like ur style - tanyasedis',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        description: 'Some not all. #slander #lgbtq #somenotall #Imreadyforthehat',
        comments: 197,
        music: 'Roxanne - Arizona Zervs',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        description: '🤫 This is my BEST resume writing secret, from my uni career advisors! #CareerAdvic',
        comments: 196,
        music: 'original sound - Daily_Handpickd',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        description: 'DM me tho 😗 #fyp #tiktoks',
        comments: 99,
        music: 'Birthday Suit - Cosmo Sheldrae',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        description: 'I left them alone for 2 mins ',
        comments: 42,
        music: 'original sound - HorizonsEclipseツ',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        description: 'Meow-nicure, need to get those stiletto nails 💅🏻 #fyp #catsoftiktok #manicure #meow #munchki',
        comments: 123,
        music: 'Unlock it (Lock It) [Jeff Prior Mix] - Charli XX',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        description: 'Một chiếc clip dành cho bạn nào muốn chụp ảnh với crush 😂😂😂 #mrvirgo #vzon',
        comments: 255,
        music: 'เสียงต้นฉบับ - 🌿🌿Sy kunza🌿',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        description: 'sometimes I confuse myself to',
        comments: 184,
        music: 'Copines ac. Isli - Bombxl',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        description: 'Reply to @zulhxl I hope this answers your questio',
        comments: 58,
        music: 'The Git Up - Benny Blano',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        description: 'bagging coffee for takeaway!! more convenient & cheaper than alternative plastic cup',
        comments: 40,
        music: 'original sound - Spinmovn',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        description: 'Write your names in comment',
        comments: 178,
        music: 'original sound - facepalmfishig',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        description: 'it do be like tha',
        comments: 19,
        music: 'original sound - Daily_Handpickd',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        description: 'Reply to @sguncle heathly day edition 🐛🐛🐛',
        comments: 53,
        music: 'Bedroom (feat. Anne-Marie) - JJ Ln',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        description: '😭😭😭😭',
        comments: 179,
        music: 'Copines ac. Isli - Bombxl',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        description: 'Behind the scenes video van giste',
        comments: 218,
        music: 'Astronaut In The Ocean - Masked Wof',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        description: '🤫 This is my BEST resume writing secret, from my uni career advisors! #CareerAdvic',
        comments: 258,
        music: 'Tag me if you make one hoes - o',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        description: 'DM me tho 😗 #fyp #tiktoksg',
        comments: 176,
        music: 'Bust Your Knee Caps - amanda',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        description: '#狮城🇸🇬🇸🇬 #高端spa #spa #按摩 #按摩舒壓放鬆服務可找我唷 #技術流 #按摩舒壓 #二店 #正规足',
        comments: 287,
        music: 'Shake Dat - by Loui (feat. Lil Ja)',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        description: 'Một chiếc clip dành cho bạn nào muốn chụp ảnh với crush 😂😂😂 #mrvirgo #vzon',
        comments: 292,
        music: 'Be A Clown - ָ࣪ ۰♥︎ Osuna ࣪꒷',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        description: 'Meow-nicure, need to get those stiletto nails 💅🏻 #fyp #catsoftiktok #manicure #meow #munchki',
        comments: 258,
        music: 'เสียงต้นฉบับ - 🌿🌿Sy kunza🌿',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        description: 'DM me tho 😗 #fyp #tiktoks',
        comments: 136,
        music: 'original sound - Daily_Handpickd',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        description: 'Keep in mind derivatives trading is haram for muslims.',
        comments: 178,
        music: 'Adams Family - Circus Bad',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        description: 'Been wanting to cover this song for a really long time, hope my pronunciation is ok!😅',
        comments: 188,
        music: 'Busta - Jphelz',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        description: 'Insta: Queenlaiba121 😼⚡️ #queenlaiba121 #pubg #pubgg',
        comments: 242,
        music: 'Men balls getting smaller - HeartScap2',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        description: '😵😵😵 #foryou #foryoupage #fyp #funn',
        comments: 155,
        music: 'Copines ac. Isli - Bombxl',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        description: 'Reply to @zulhxl I hope this answers your questio',
        comments: 175,
        music: 'เสียงต้นฉบับ - 🌿🌿Sy kunza🌿',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        description: 'Im clearly joking, right? Right. Unless..',
        comments: 168,
        music: 'baby I like ur style - tanyasedis',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        description: 'Ep. 2 Do you tell your siblings everything? #truth #brothe',
        comments: 224,
        music: 'Unlock it (Lock It) [Jeff Prior Mix] - Charli XX',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        description: 'I check the price... I put it back ',
        comments: 34,
        music: 'Somebody to love Basstrologe Bootleg - mthekyg',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        description: 'What Chinese will sound like in 50 years! #mryang楊家',
        comments: 135,
        music: 'Adams Family - Circus Bad',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        description: 'Ep. 2 Do you tell your siblings everything? #truth #brothe',
        comments: 287,
        music: 'Busta - Jphelz',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        description: 'I left them alone for 2 mins ',
        comments: 48,
        music: 'Birthday Suit - Cosmo Sheldrae',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        description: 'Ụi ụi nhanh nhanh không cơm nguội #cliphai #funny #haihuo',
        comments: 75,
        music: "Whatta Man (feat. En Vogue) [EP Version] - Salt 'N' Pea",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 9,
        description: 'When they say they’re from U.S.A... #fyp #tiktoksingapore #us',
        comments: 209,
        music: 'The Git Up - Benny Blano',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 9,
        description: 'What Chinese will sound like in 50 years! #mryang楊家',
        comments: 136,
        music: 'Shake Dat - by Loui (feat. Lil Ja)',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 9,
        description: 'What Chinese will sound like in 50 years! #mryang楊家',
        comments: 28,
        music: 'Shake Dat - by Loui (feat. Lil Ja)',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 9,
        description: 'Have you seen something so interesting fruits? #fruit',
        comments: 148,
        music: 'nhạc nền - Vũ Thị Khánh Huyn',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        description: 'How to Escape',
        comments: 242,
        music: 'Busta - Jphelpz',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        description: 'Abang Bomba 🥵🔥 ',
        comments: 289,
        music: 'O Carpinteiro (Conto de Fadas) - nattan & Elias Monkbel',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        description: 'sometimes I confuse myself too',
        comments: 45,
        music: 'All Time Low - Jon Bellion',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        description: 'Have you seen something so interesting fruits? #fruits',
        comments: 299,
        music: 'original sound - Laiba 👸🏻',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        description: 'sometimes I confuse myself too',
        comments: 173,
        music: "Whatta Man (feat. En Vogue) [EP Version] - Salt 'N' Pepa",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        description: 'Im clearly joking, right? Right. Unless...',
        comments: 224,
        music: 'original sound - Spinmovin',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        description: '🇳🇵 this is PPG mc, #all_point_of_technical #paramotor',
        comments: 26,
        music: 'original sound - Daily_Handpicked',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        description: 'Been wanting to cover this song for a really long time, hope my pronunciation is ok!😅 ',
        comments: 130,
        music: 'Bad Guy - Billie Eilish',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        description: '역대급 락스피릿 소유자ㅋㅋㅋㅋ #몰카 #부평 #몰래카메라',
        comments: 190,
        music: 'Дикая львица - ALEX&RUS',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        description: 'uni is reeeally expensive (pt 2 coming tmr bc the whole video was too long 😭)',
        comments: 158,
        music: 'original sound - Spinmovin',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 11,
        description: 'Ụi ụi nhanh nhanh không cơm nguội #cliphai #funny #haihuoc',
        comments: 115,
        music: 'Astronaut In The Ocean - Masked Wolf',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 11,
        description: 'I check the price... I put it back 🥲',
        comments: 110,
        music: 'Дикая львица - ALEX&RUS',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 11,
        description: 'There are times when I just want to be quiet.',
        comments: 232,
        music: 'Bedroom (feat. Anne-Marie) - JJ Lin',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 11,
        description: 'dễ thương quá 🥰🥰🥰 #tiktok #NANNO #thocon #fo',
        comments: 121,
        music: 'How You Like That - BLACKPINK',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 11,
        description: 'I check the price... I put it back 🥲',
        comments: 66,
        music: 'Bust Your Knee Caps - amanda',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 11,
        description: 'Insta: Queenlaiba121 😼⚡️ #queenlaiba121 #pubg #pubggg',
        comments: 177,
        music: 'Lofi Lounge musicc - Cafe lounge resort',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 12,
        description: 'Reply to @zulhxl I hope this answers your question',
        comments: 153,
        music: 'Copines ac. Isli - Bombxel',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 12,
        description: 'Im clearly joking, right? Right. Unless...',
        comments: 168,
        music: 'Lofi Lounge musicc - Cafe lounge resort',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'wbu ? #animegirl',
        comments: 58,
        music: 'Men balls getting smaller - HeartScape2',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'Ep. 2 Do you tell your siblings everything? #truth #brother',
        comments: 181,
        music: 'Be A Clown - ָ࣪ ۰♥︎ Osuna ࣪𖥔꒷',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'Write your names in comment!',
        comments: 125,
        music: 'original sound - Daily_Handpicked',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'DM me tho 😗 #fyp #tiktoksg',
        comments: 247,
        music: 'original sound - Daily_Handpicked',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'Chase your Goals 👑 #fyp #sgfyp',
        comments: 129,
        music: 'How You Like That - BLACKPINK',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'wbu ? #animegirl',
        comments: 217,
        music: 'Adams Family - Circus Band',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: '역대급 락스피릿 소유자ㅋㅋㅋㅋ #몰카 #부평 #몰래카메라',
        comments: 68,
        music: 'How You Like That - BLACKPINK',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'Ep. 2 Do you tell your siblings everything? #truth #brother',
        comments: 38,
        music: 'Bad Guy - Billie Eilish',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'interesting cat #cat #pet #cute #catsoftiktok #foryou #fyp',
        comments: 206,
        music: 'original sound - user9942938153949',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'Have you seen something so interesting fruits? #fruits',
        comments: 228,
        music: 'Bust Your Knee Caps - amanda',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'Meow-nicure, need to get those stiletto nails 💅🏻 #fyp #catsoftiktok #manicure #meow #munchkin',
        comments: 238,
        music: 'The Git Up - Benny Blanco',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        description: 'How to Escape',
        comments: 170,
        music: 'Astronaut In The Ocean - Masked Wolf',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        description: 'a ha ha',
        comments: 166,
        music: 'Men balls getting smaller - HeartScape2',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        description: 'Write your names in comment!',
        comments: 40,
        music: 'original sound - 😈😈😈ရုပ္ဆိုးမေလး😢🥺👿👿👿 - 🌻🌼🌞🌸🌹pi🌻🌼',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        description: '#狮城🇸🇬🇸🇬 #高端spa #spa #按摩 #按摩舒壓放鬆服務可找我唷 #技術流 #按摩舒壓 #二店 #正规足疗',
        comments: 68,
        music: 'How You Like That - BLACKPINK',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        description: 'sometimes I confuse myself too',
        comments: 67,
        music: 'original sound - user9942938153949',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        description: 'Nice guys finish last, that’s why I treat you like trash ❤️(ib: @christian_davis20 ) #fyp #tiktoksg #fuccboi',
        comments: 139,
        music: 'Somebody to love Basstrologe Bootleg - mthekyng',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        description: 'After many years later, I met my high school bullies. #fyp #foryoupage #tiktoksg #highschool',
        comments: 60,
        music: 'original sound - facepalmfishing',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        description: 'DM me tho 😗 #fyp #tiktoksg',
        comments: 52,
        music: 'original sound - Football Tekkers',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        description: 'just wondering ;)',
        comments: 122,
        music: 'Lose You to Love Me - Selena Gomez',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        description: '#狮城🇸🇬🇸🇬 #高端spa #spa #按摩 #按摩舒壓放鬆服務可找我唷 #技術流 #按摩舒壓 #二店 #正规足疗',
        comments: 162,
        music: 'original sound - Daily_Handpicked',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        description: 'Write your names in comment!',
        comments: 221,
        music: 'Be A Clown - ָ࣪ ۰♥︎ Osuna ࣪𖥔꒷',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        description: 'Ep. 2 Do you tell your siblings everything? #truth #brother',
        comments: 292,
        music: 'Shake Dat - by Loui (feat. Lil Jay)',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        description: 'The second part of the face off came out today. They will officially be taking each other in a 3 round fight 👊',
        comments: 186,
        music: 'Birthday Suit - Cosmo Sheldrake',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'After many years later, I met my high school bullies. #fyp #foryoupage #tiktoksg #highschool',
        comments: 125,
        music: 'Unlock it (Lock It) [Jeff Prior Mix] - Charli XCX',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'dễ thương quá 🥰🥰🥰 #tiktok #NANNO #thocon #fo',
        comments: 107,
        music: 'baby I like ur style - tanyasedits',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'no srsly is 3pm why r u running',
        comments: 294,
        music: 'original sound - Timmitio',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'wbu ? #animegirl',
        comments: 43,
        music: 'Birthday Suit - Cosmo Sheldrake',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'bagging coffee for takeaway!! more convenient & cheaper than alternative plastic cups',
        comments: 178,
        music: 'Somebody to love Basstrologe Bootleg - mthekyng',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'えのきステーキ / enoki mushroom steak #食べる #食テロ #tiktokfood #tiktokอาหาร',
        comments: 285,
        music: 'original sound - Timmitio',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'Abang Bomba 🥵🔥 ',
        comments: 42,
        music: 'YRN (tik tok) - Tyler April',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'Abang Bomba 🥵🔥 ',
        comments: 42,
        music: 'Lose You to Love Me - Selena Gomez',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        description: 'Reply to @zulhxl I hope this answers your question',
        comments: 74,
        music: 'Candy - Doja Cat',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 15,
        description: 'sorry ive only watched one anime my whole life//',
        comments: 294,
        music: 'Cherrybonbon - Kyary Pamyu Pamyu',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 15,
        description: 'Ep. 2 Do you tell your siblings everything? #truth #brother',
        comments: 299,
        music: 'Lofi Lounge musicc - Cafe lounge resort',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 16,
        description: 'Behind the scenes video van gister',
        comments: 189,
        music: '오리지널 사운드 - 윤조',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 16,
        description: 'Behind the scenes video van gister',
        comments: 25,
        music: 'original sound - Clarambles',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 16,
        description: 'I check the price... I put it back 🥲',
        comments: 82,
        music: 'original sound - facepalmfishing',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 16,
        description: 'Yes throw out your razors use an epilator. Tried, tested and verified',
        comments: 298,
        music: 'Unlock it (Lock It) [Jeff Prior Mix] - Charli XCX',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 16,
        description: 'えのきステーキ / enoki mushroom steak #食べる #食テロ #tiktokfood #tiktokอาหาร',
        comments: 199,
        music: 'nhạc nền - Vũ Thị Khánh Huyền',
        created_at: new Date(),
        updated_at: new Date(),
      },

    ];

    videosList.forEach((video, index) => {
      video.url = mixkitVideos[index];
    });

    const likesList = [
      {
        user_id: 11,
        video_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 16,
        video_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        video_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        video_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 17,
        video_id: 5,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        video_id: 6,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        video_id: 7,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        video_id: 8,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        video_id: 9,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        video_id: 10,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 16,
        video_id: 11,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        video_id: 12,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        video_id: 13,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        video_id: 14,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 17,
        video_id: 15,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        video_id: 16,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        video_id: 17,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        video_id: 18,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        video_id: 19,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        video_id: 20,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 11,
        video_id: 21,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        video_id: 22,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 12,
        video_id: 23,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        video_id: 24,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        video_id: 25,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        video_id: 26,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        video_id: 27,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        video_id: 28,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        video_id: 29,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        video_id: 30,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        video_id: 31,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 16,
        video_id: 32,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        video_id: 33,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        video_id: 34,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        video_id: 35,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        video_id: 36,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        video_id: 37,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        video_id: 38,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 11,
        video_id: 39,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        video_id: 40,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        video_id: 41,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        video_id: 42,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        video_id: 43,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 11,
        video_id: 44,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 15,
        video_id: 45,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        video_id: 46,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 9,
        video_id: 47,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 17,
        video_id: 48,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        video_id: 49,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        video_id: 50,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        video_id: 51,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 9,
        video_id: 52,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        video_id: 53,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 17,
        video_id: 54,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        video_id: 55,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        video_id: 56,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 15,
        video_id: 57,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 15,
        video_id: 58,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        video_id: 59,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 17,
        video_id: 60,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        video_id: 61,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        video_id: 62,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 16,
        video_id: 63,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        video_id: 64,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        video_id: 65,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        video_id: 66,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        video_id: 67,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 11,
        video_id: 68,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        video_id: 69,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        video_id: 70,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 11,
        video_id: 71,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 15,
        video_id: 72,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 12,
        video_id: 73,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        video_id: 74,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        video_id: 75,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 15,
        video_id: 76,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        video_id: 77,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        video_id: 78,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        video_id: 79,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        video_id: 80,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        video_id: 81,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        video_id: 82,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        video_id: 83,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 11,
        video_id: 84,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 15,
        video_id: 85,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        video_id: 86,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        video_id: 87,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        video_id: 88,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        video_id: 89,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 17,
        video_id: 90,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 17,
        video_id: 91,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 16,
        video_id: 92,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        video_id: 93,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        video_id: 94,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        video_id: 95,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        video_id: 96,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        video_id: 97,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        video_id: 98,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        video_id: 99,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        video_id: 99,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 9,
        video_id: 100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        video_id: 101,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 16,
        video_id: 102,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 9,
        video_id: 103,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        video_id: 104,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        video_id: 105,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 12,
        video_id: 106,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 1,
        video_id: 107,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 16,
        video_id: 108,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        video_id: 109,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        video_id: 110,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        video_id: 111,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        video_id: 112,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 15,
        video_id: 113,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        video_id: 114,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        video_id: 115,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 15,
        video_id: 116,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        video_id: 117,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        video_id: 118,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 15,
        video_id: 119,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 16,
        video_id: 120,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 14,
        video_id: 121,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 9,
        video_id: 122,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        video_id: 123,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 17,
        video_id: 124,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        video_id: 125,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 9,
        video_id: 126,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 13,
        video_id: 127,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        video_id: 128,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 17,
        video_id: 129,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        video_id: 130,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        video_id: 131,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        video_id: 132,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 11,
        video_id: 133,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 10,
        video_id: 134,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        video_id: 135,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ];

    const followList = [
      {
        followed_id: 1,
        follower_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        followed_id: 1,
        follower_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        followed_id: 1,
        follower_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        followed_id: 1,
        follower_id: 5,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        followed_id: 2,
        follower_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        followed_id: 2,
        follower_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        followed_id: 2,
        follower_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        followed_id: 2,
        follower_id: 5,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ];

    try {
      await queryInterface.bulkInsert('users', usersList);
      await queryInterface.bulkInsert('videos', videosList);
      await queryInterface.bulkInsert('likes', likesList);
      await queryInterface.bulkInsert('follows', followList);
    } catch (error) {
      console.log(error);
    }
  },

  down: async (queryInterface) => {
    await queryInterface.bulkDelete('follows', null, {});
    await queryInterface.bulkDelete('likes', null, {});
    await queryInterface.bulkDelete('videos', null, {});
    await queryInterface.bulkDelete('users', null, {});
  },
};
